# Generated by Django 4.0.4 on 2022-07-04 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='source',
            field=models.CharField(choices=[('fitness', 'Fitness'), ('reduce_weight', 'Reduce Weight'), ('increase_weight', 'Increase Weight'), ('hyper_trophy', 'Hyper Trophy')], default='fitness', max_length=225),
        ),
    ]
