# Generated by Django 4.0.4 on 2022-07-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_password_alter_attendance_attendance_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
