# Generated by Django 4.0.4 on 2022-07-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_first_name_profile_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Membership',
            new_name='membership',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Post_code',
            new_name='post_code',
        ),
    ]
