# Generated by Django 4.0.4 on 2022-07-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_approved_profile_profile_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='membership_expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='membership_updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
