# Generated by Django 4.0.4 on 2022-07-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_membership_expires_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='membership_expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='membership_updated_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
