# Generated by Django 4.0.4 on 2022-07-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_membership_expires_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, default=0)),
                ('comments', models.TextField(blank=True, max_length=500)),
                ('transaction', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], default='debit', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
