# Generated by Django 4.0.4 on 2022-07-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='source',
            new_name='purpose',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transaction',
            field=models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], default='credit', max_length=9),
        ),
    ]
